version: '2'
services:
  shopfront:
    image: cavva/oreillyshoptest
    ports:
     - "8010:8010"
    links:
      - productcatalogue
      - stockmanager
  productcatalogue:
    image: cavva/oreillycataloguetest
    ports:
     - "8020:8020"
  stockmanager:
    image: cavva/oreillystocktest
    ports:
     - "8030:8030"
